# Generated by Django 6.0.6 on 2026-06-16 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UpperBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(blank=True)),
                ('shoulder', models.IntegerField(blank=True)),
                ('armLength', models.IntegerField(blank=True)),
                ('fourarmLength', models.IntegerField(blank=True)),
                ('neck', models.IntegerField(blank=True)),
                ('chest', models.IntegerField(blank=True)),
                ('waist', models.IntegerField(blank=True)),
                ('hips', models.IntegerField(blank=True)),
                ('clothType', models.CharField(choices=[(' ', ' '), ('Shirt', 'Shirt'), ('Kurta', 'Kurta'), ('Kurti', 'Kurti'), ('Shrewani', 'Shrewani'), ('Coat', 'Coat'), ('Jacket', 'Jacket'), ('Blouse', 'Blouse'), ('Gown', 'Gown'), ('Frock', 'Frock')], default='None', max_length=20)),
                ('pocket', models.BooleanField(default=False)),
                ('requirments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloths.options')),
            ],
        ),
    ]
