# Generated by Django 5.2.15 on 2026-06-16 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LowerBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(default=0)),
                ('hips', models.IntegerField(default=0)),
                ('thigh', models.IntegerField(default=0)),
                ('knee', models.IntegerField(default=0)),
                ('ankle', models.IntegerField(default=0)),
                ('pantBottom', models.IntegerField(default=0)),
                ('uCrouch', models.IntegerField(default=0)),
                ('Clothtype', models.CharField(choices=[(' ', ' '), ('Pant', 'Pant'), ('Barmuda', 'Barmuda'), ('Paijama', 'Paijama'), ('Skirt', 'Skirt'), ('Leggings', 'Leggings')], default=' ', max_length=20)),
                ('requirements', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cloths.options')),
            ],
        ),
        migrations.CreateModel(
            name='UpperBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(default=0)),
                ('chest', models.IntegerField(default=0)),
                ('upperChest', models.IntegerField(default=0)),
                ('waist', models.IntegerField(default=0)),
                ('hips', models.IntegerField(default=0)),
                ('shoulder', models.IntegerField(default=0)),
                ('sleeves', models.IntegerField(default=0)),
                ('biceps', models.IntegerField(default=0)),
                ('armHold', models.IntegerField(default=0)),
                ('elbow', models.IntegerField(default=0)),
                ('collar', models.IntegerField(default=0)),
                ('backLength', models.IntegerField(default=0)),
                ('crossBack', models.IntegerField(default=0)),
                ('bustLength', models.IntegerField(default=0)),
                ('apexGap', models.IntegerField(default=0)),
                ('bottomWidth', models.IntegerField(default=0)),
                ('clothType', models.CharField(choices=[(' ', ' '), ('Shirt', 'Shirt'), ('Kurta', 'Kurta'), ('Kurti', 'Kurti'), ('Shrewani', 'Shrewani'), ('Coat', 'Coat'), ('Jacket', 'Jacket'), ('Blouse', 'Blouse'), ('Gown', 'Gown'), ('Frock', 'Frock')], default=' ', max_length=20)),
                ('pocket', models.BooleanField(default=False)),
                ('requirments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cloths.options')),
            ],
        ),
    ]
