# Generated by Django 6.0.6 on 2026-06-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LowerBody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("length", models.IntegerField(blank=True)),
                ("hips", models.IntegerField(blank=True)),
                ("thies", models.IntegerField(blank=True)),
                ("knee", models.IntegerField(blank=True)),
                ("ankle", models.IntegerField(blank=True)),
                (
                    "Clothtype",
                    models.CharField(
                        choices=[
                            (" ", " "),
                            ("Pant", "Pant"),
                            ("Barmuda", "Barmuda"),
                            ("Paijama", "Paijama"),
                            ("Skirt", "Skirt"),
                            ("Leggings", "Leggings"),
                            ("Leggings", "Leggings"),
                        ],
                        default="None",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
