# Generated by Django 5.2.15 on 2026-06-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lowerbody',
            old_name='Clothtype',
            new_name='clothType',
        ),
        migrations.AddField(
            model_name='upperbody',
            name='button',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Snap', 'Snap'), ('Flat Shank', 'Flat Shank'), ('Hook', 'Hook')], default='Normal', max_length=20),
        ),
        migrations.AddField(
            model_name='upperbody',
            name='sleeveType',
            field=models.CharField(choices=[('Full', 'Full'), ('Half', 'Half'), ('No Sleeve', 'No Sleeve')], default='Full', max_length=20),
        ),
    ]
