# Generated by Django 5.2.15 on 2026-06-16 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0002_rename_clothtype_lowerbody_clothtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowerbody',
            name='requirements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cloths.options'),
        ),
        migrations.AlterField(
            model_name='upperbody',
            name='requirments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cloths.options'),
        ),
    ]
