# Generated by Django 5.2.15 on 2026-06-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0003_alter_lowerbody_requirements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowerbody',
            name='clothType',
            field=models.CharField(choices=[(' ', ' '), ('Trouser', 'Trouser'), ('Barmuda', 'Barmuda'), ('Paijama', 'Paijama'), ('Skirt', 'Skirt'), ('Leggings', 'Leggings')], default=' ', max_length=20),
        ),
    ]
