# Generated by Django 5.2.15 on 2026-06-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0004_alter_lowerbody_clothtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_type', models.CharField(choices=[(' ', ' '), ('Trouser', 'Trouser'), ('Barmuda', 'Barmuda'), ('Paijama', 'Paijama'), ('Skirt', 'Skirt'), ('Leggings', 'Leggings'), (' ', ' '), ('Shirt', 'Shirt'), ('Kurta', 'Kurta'), ('Kurti', 'Kurti'), ('Shrewani', 'Shrewani'), ('Coat', 'Coat'), ('Jacket', 'Jacket'), ('Blouse', 'Blouse'), ('Gown', 'Gown'), ('Frock', 'Frock')], default=' ', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
