# Generated by Django 5.2.15 on 2026-06-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0006_alter_clothprice_cloth_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothprice',
            name='cloth_type',
            field=models.CharField(choices=[('Trouser', 'Trouser'), ('Barmuda', 'Barmuda'), ('Paijama', 'Paijama'), ('Skirt', 'Skirt'), ('Leggings', 'Leggings'), ('Shirt', 'Shirt'), ('Kurta', 'Kurta'), ('Kurti', 'Kurti'), ('Shrewani', 'Shrewani'), ('Coat', 'Coat'), ('Jacket', 'Jacket'), ('Blouse', 'Blouse'), ('Gown', 'Gown'), ('Frock', 'Frock')], default=' ', max_length=20, unique=True),
        ),
    ]
