# Generated by Django 6.0.6 on 2026-06-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0007_alter_clothprice_cloth_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothprice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lowerbody',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='options',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='upperbody',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
