# Generated by Django 6.0.6 on 2026-06-17 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auths', '0002_rename_gender_appuser_gender'),
        ('cloths', '0008_alter_clothprice_id_alter_lowerbody_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time', models.DateTimeField(auto_now=True)),
                ('out_time', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auths.appuser')),
                ('lowerBody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloths.lowerbody')),
                ('upperBody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloths.upperbody')),
            ],
        ),
    ]
