# Generated by Django 6.0.6 on 2026-06-17 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
        ('cloths', '0008_alter_clothprice_id_alter_lowerbody_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lowerBody',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cloths.lowerbody'),
        ),
        migrations.AlterField(
            model_name='order',
            name='upperBody',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cloths.upperbody'),
        ),
    ]
