# Generated by Django 6.0.6 on 2026-06-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_alter_order_lowerbody_alter_order_upperbody'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Waiting', 'Waiting'), ('Urgent', 'Urgent'), ('Done', 'Done')], default='New', max_length=20),
        ),
    ]
