# Generated by Django 5.2.15 on 2026-06-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='days',
            field=models.PositiveIntegerField(default=7, help_text='Days to complete the order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='in_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
