# Generated by Django 5.2.15 on 2026-06-15 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auths', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='Gender',
            new_name='gender',
        ),
    ]
