# Generated by Django 6.0.6 on 2026-06-17 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cloths', '0008_alter_clothprice_id_alter_lowerbody_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaning', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_price', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cloths.clothprice')),
            ],
        ),
    ]
