# Generated by Django 6.0.6 on 2026-06-17 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Billing', '0001_initial'),
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Order.order'),
        ),
    ]
